name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -f tests/TestMakefile -k build
    - name: Test Array Template
      run: make -f tests/TestMakefile -k arrayTest
    - name: Test Str Class
      run: make -f tests/TestMakefile -k strTest
    - name: Test Symbol Table Class
      run: make -f tests/TestMakefile -k symTest
    - name: Test Dict Template
      run: make -f tests/TestMakefile -k dictTest
    - name: Clean Test Executables
      run: make -f tests/TestMakefile -k clean